name: Main

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  initialize:
    name: Initialize
    uses: ./.github/workflows/initialize.yml

  verify:
    name: Verify
    needs: initialize
    uses: ./.github/workflows/verify.yml

  build:
    name: Build
    needs: verify
    uses: ./.github/workflows/build.yml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml
